export const ADD_LIST = 'ADD_LIST'

export const DELETE_LIST = 'DELETE_LIST'

export const CLEAR_COMPLETED_LIST = 'CLEAR_COMPLETED_LIST'

export const FILTER_ALL_LIST = 'FILTER_ALL_LIST'

export const FILTER_ACTIVE_LIST = 'FILTER_ACTIVE_LIST'

export const FILTER_COMPLETETED_LIST = 'FILTER_COMPLETETED_LIST'

export const CHECK_LIST = 'CHECK_LIST'

export const ON_DRAG_LIST = 'ON_DRAG_LIST'